import { CardData } from './types';

export const OFFICIAL_52_CARDS: CardData[] = [
  {
    id: 'c1',
    category: 'C',
    name: 'Krishna',
    points: 8,
    ruler: 'Krishna',
    rulerId: 'krishna',
    rulerName: 'Krishna',
    symbol: '🦚',
    immediateFather: null,
    immediateSon: 'Arjuna (Kin)',
    detail: 'The Supreme Guide and avatar of Vishnu who established righteousness. Master diplomat at the Hastinapura peace embassy and charioteer to Arjuna at Kurukshetra.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l1',
    category: 'L',
    name: 'Krishna\'s Counsel — Krishna',
    points: 6,
    ruler: 'Krishna',
    rulerId: 'krishna',
    rulerName: 'Krishna',
    symbol: '📜',
    immediateFather: null,
    immediateSon: null,
    detail: 'The immortal moral and strategic wisdom imparted by Krishna—guiding Yudhishthira toward righteousness and counselling the warrior princes through the darkest tribulations.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm1',
    category: 'M',
    name: 'Sudarshana Chakra',
    points: 4,
    ruler: 'Krishna',
    rulerId: 'krishna',
    rulerName: 'Krishna',
    symbol: '☸️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The supreme spinning discus of cosmic fire, bearing 108 serrated edges, capable of cleaving any defense and upholding Dharma across all three worlds.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r1',
    category: 'R',
    name: 'Dwaraka',
    points: 2,
    ruler: 'Krishna',
    rulerId: 'krishna',
    rulerName: 'Krishna',
    symbol: '🌊',
    immediateFather: null,
    immediateSon: null,
    detail: 'The submerged golden citadel on the western sea, built by Vishwakarma with ramparts of gold and crystalline towers, sanctuary of the Vrishnis and Yadavas.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c2',
    category: 'C',
    name: 'Yudhishthira',
    points: 8,
    ruler: 'Yudhishthira',
    rulerId: 'yudhishthira',
    rulerName: 'Yudhishthira',
    symbol: '👑',
    immediateFather: 'Dharma',
    immediateSon: 'Bhima (Brother)',
    detail: 'Dharmaraja, crowned King of Indraprastha and Hastinapura. Victor of the Rajasuya sacrifice whose devotion to truth guided the Pandavas through exile and war.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l2',
    category: 'L',
    name: 'Rajadharma — Yudhishthira',
    points: 6,
    ruler: 'Yudhishthira',
    rulerId: 'yudhishthira',
    rulerName: 'Yudhishthira',
    symbol: '⚖️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The noble principles of righteous kingship: compassion toward subjects, protection of the vulnerable, and adherence to moral duty even in the face of ruin.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm2',
    category: 'M',
    name: 'Akshaya Patra',
    points: 4,
    ruler: 'Yudhishthira',
    rulerId: 'yudhishthira',
    rulerName: 'Yudhishthira',
    symbol: '🍲',
    immediateFather: null,
    immediateSon: null,
    detail: 'The inexhaustible copper vessel bestowed by Surya the Sun God to Yudhishthira during forest exile, providing endless divine sustenance until Draupadi finished her meal.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r2',
    category: 'R',
    name: 'Indraprastha',
    points: 2,
    ruler: 'Yudhishthira',
    rulerId: 'yudhishthira',
    rulerName: 'Yudhishthira',
    symbol: '🏰',
    immediateFather: null,
    immediateSon: null,
    detail: 'The resplendent capital founded by the Pandavas in the cleared Khandava tract, renowned for wide avenues, moated fortifications, and celestial splendor.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c3',
    category: 'C',
    name: 'Bhima',
    points: 8,
    ruler: 'Bhima',
    rulerId: 'bhima',
    rulerName: 'Bhima',
    symbol: '🐯',
    immediateFather: 'Yudhishthira (Elder)',
    immediateSon: 'Arjuna (Brother)',
    detail: 'The indomitable warrior possessing unmatched colossal strength. Slaying Jarasandha, Kichaka, and Dushasana, he fulfilled every vow with unrelenting valor.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l3',
    category: 'L',
    name: 'Bhima\'s Vow — Bhima',
    points: 6,
    ruler: 'Bhima',
    rulerId: 'bhima',
    rulerName: 'Bhima',
    symbol: '🔥',
    immediateFather: null,
    immediateSon: null,
    detail: 'The unbreakable warrior oath sworn in the royal court to protect righteousness, destroy the oppressors, and wash Draupadi\'s unbound hair with the blood of justice.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm3',
    category: 'M',
    name: 'Kaumodaki Gada',
    points: 4,
    ruler: 'Bhima',
    rulerId: 'bhima',
    rulerName: 'Bhima',
    symbol: '🔨',
    immediateFather: null,
    immediateSon: null,
    detail: 'The thunderous divine mace crafted of celestial gold and meteor iron, swinging with the force of mountain storms to shatter iron armor and chariot walls.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r3',
    category: 'R',
    name: 'Magadha',
    points: 2,
    ruler: 'Bhima',
    rulerId: 'bhima',
    rulerName: 'Bhima',
    symbol: '⛰️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The ancient fortress realm of Girivraja, surrounded by five jagged hills, where Bhima engaged the formidable King Jarasandha in a historic fourteen-day wrestling duel.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c4',
    category: 'C',
    name: 'Arjuna',
    points: 8,
    ruler: 'Arjuna',
    rulerId: 'arjuna',
    rulerName: 'Arjuna',
    symbol: '🏹',
    immediateFather: 'Bhima (Elder)',
    immediateSon: 'Abhimanyu (Son)',
    detail: 'The legendary warrior of focused sight who won Draupadi at the swayamvara, vanquished the Nivatakavachas, and turned the tide of the great Kurukshetra war.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l4',
    category: 'L',
    name: 'Arjuna\'s Duty — Arjuna',
    points: 6,
    ruler: 'Arjuna',
    rulerId: 'arjuna',
    rulerName: 'Arjuna',
    symbol: '🛡️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The profound Kshatriya dharma of rising above hesitation, upholding righteousness without attachment, and fighting steadfastly to restore moral order in the cosmos.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm4',
    category: 'M',
    name: 'Gandiva Bow',
    points: 4,
    ruler: 'Arjuna',
    rulerId: 'arjuna',
    rulerName: 'Arjuna',
    symbol: '⚡',
    immediateFather: null,
    immediateSon: null,
    detail: 'The divine celestial bow gifted by Agni and Varuna, inlaid with gold, capable of shooting hundreds of blazing arrows in a split second with lightning resonance.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r4',
    category: 'R',
    name: 'Kamyaka Forest',
    points: 2,
    ruler: 'Arjuna',
    rulerId: 'arjuna',
    rulerName: 'Arjuna',
    symbol: '🌲',
    immediateFather: null,
    immediateSon: null,
    detail: 'The sacred enchanted wilderness along the banks of the Saraswati, where the Pandavas resided during exile and where sages imparted divine knowledge.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c5',
    category: 'C',
    name: 'Karna',
    points: 8,
    ruler: 'Karna',
    rulerId: 'karna',
    rulerName: 'Karna',
    symbol: '☀️',
    immediateFather: 'Surya (Father)',
    immediateSon: 'Vrishakethu (Son)',
    detail: 'The supreme archer and loyal King of Anga whose generosity was absolute. A master of celestial astras who stood fearless against all odds on the seventeenth day.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l5',
    category: 'L',
    name: 'Karna\'s Charity — Karna',
    points: 6,
    ruler: 'Karna',
    rulerId: 'karna',
    rulerName: 'Karna',
    symbol: '🪙',
    immediateFather: null,
    immediateSon: null,
    detail: 'Danaveera Karna never turned away a seeker. He willingly cut off his inborn golden armor (Kavacha) and divine earrings (Kundala) for Indra disguised as a brahmana.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm5',
    category: 'M',
    name: 'Brahmastra',
    points: 4,
    ruler: 'Karna',
    rulerId: 'karna',
    rulerName: 'Karna',
    symbol: '☄️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The terrifying weapon of cosmic destruction created by Lord Brahma, capable of incinerating legions, learned by Karna under the rigorous tutelage of sage Parashurama.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r5',
    category: 'R',
    name: 'Kurukshetra',
    points: 2,
    ruler: 'Karna',
    rulerId: 'karna',
    rulerName: 'Karna',
    symbol: '⚔️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The sacred Dharmakshetra field of destiny where the eighteen-day epic war was fought, bearing witness to Karna\'s final heroic stand and tragic ascension.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c6',
    category: 'C',
    name: 'Bhishma',
    points: 8,
    ruler: 'Bhishma',
    rulerId: 'bhishma',
    rulerName: 'Bhishma',
    symbol: '🛡️',
    immediateFather: 'Shantanu (Father)',
    immediateSon: 'Dhritarashtra (Ward)',
    detail: 'The grand patriarch of the Kurus whose martial skill and ethical stature commanded universal reverence. Supreme commander of the Kaurava army for the first ten days.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l6',
    category: 'L',
    name: 'Bhishma\'s Vow — Bhishma',
    points: 6,
    ruler: 'Bhishma',
    rulerId: 'bhishma',
    rulerName: 'Bhishma',
    symbol: '❄️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The terrible vow (Bhishma Pratigya) of lifelong brahmacharya and renunciation of the crown to ensure his father Shantanu\'s happiness, earning him his revered name.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm6',
    category: 'M',
    name: 'Pashupatastra',
    points: 4,
    ruler: 'Bhishma',
    rulerId: 'bhishma',
    rulerName: 'Bhishma',
    symbol: '🔱',
    immediateFather: null,
    immediateSon: null,
    detail: 'The supreme celestial projectile of Mahadeva Shiva, wielded with devastating cosmic power, capable of wiping out all creation when invoked with righteous intent.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r6',
    category: 'R',
    name: 'Hastinapura',
    points: 2,
    ruler: 'Bhishma',
    rulerId: 'bhishma',
    rulerName: 'Bhishma',
    symbol: '🐘',
    immediateFather: null,
    immediateSon: null,
    detail: 'The legendary city of the Elephant Gate, imperial seat of the Kuru throne along the sacred Ganga, guarded and preserved by Bhishma for generations.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c7',
    category: 'C',
    name: 'Dronacharya',
    points: 8,
    ruler: 'Dronacharya',
    rulerId: 'dronacharya',
    rulerName: 'Dronacharya',
    symbol: '🏹',
    immediateFather: 'Bharadwaja (Father)',
    immediateSon: 'Ashwatthama (Son)',
    detail: 'The royal guru of celestial weaponry whose tactical mastery and fierce combat prowess shook the battlefield of Kurukshetra during his five days as supreme commander.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l7',
    category: 'L',
    name: 'Guru-Dakshina — Dronacharya',
    points: 6,
    ruler: 'Dronacharya',
    rulerId: 'dronacharya',
    rulerName: 'Dronacharya',
    symbol: '🎯',
    immediateFather: null,
    immediateSon: null,
    detail: 'The sacred bond between guru and disciple, exemplified when Drona demanded the defeat and capture of King Drupada of Panchala as his disciples\' final offering.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm7',
    category: 'M',
    name: 'Bhagavad Gita Teachings',
    points: 4,
    ruler: 'Dronacharya',
    rulerId: 'dronacharya',
    rulerName: 'Dronacharya',
    symbol: '📖',
    immediateFather: null,
    immediateSon: null,
    detail: 'The immortal eighteen chapters of divine dialogue between Krishna and Arjuna, unveiling the eternal pathways of Karma Yoga, Bhakti Yoga, and Jnana Yoga.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r7',
    category: 'R',
    name: 'Panchala',
    points: 2,
    ruler: 'Dronacharya',
    rulerId: 'dronacharya',
    rulerName: 'Dronacharya',
    symbol: '🏛️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The ancient realm of King Drupada divided by the holy river Ganga, northern half granted to Drona as teacher\'s homage by the victorious Pandava disciples.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c8',
    category: 'C',
    name: 'Duryodhana',
    points: 8,
    ruler: 'Duryodhana',
    rulerId: 'duryodhana',
    rulerName: 'Duryodhana',
    symbol: '⚔️',
    immediateFather: 'Dhritarashtra (Father)',
    immediateSon: 'Lakshmana (Son)',
    detail: 'The fierce leader of the Kauravas whose unyielding pride and martial prowess defined the conflict. He refused to yield even five needles of land without a trial of arms.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l8',
    category: 'L',
    name: 'Shanti & Dharma Teachings — Bhishma',
    points: 6,
    ruler: 'Duryodhana',
    rulerId: 'duryodhana',
    rulerName: 'Duryodhana',
    symbol: '🕊️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The profound post-war discourses delivered by Bhishma from his bed of arrows, expounding the Shanti Parva and Anushasana Parva on justice, governance, and peace.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm8',
    category: 'M',
    name: 'Mayasabha',
    points: 4,
    ruler: 'Duryodhana',
    rulerId: 'duryodhana',
    rulerName: 'Duryodhana',
    symbol: '✨',
    immediateFather: null,
    immediateSon: null,
    detail: 'The magical assembly hall designed by Danava architect Maya for the Pandavas, filled with optical illusions of liquid crystal floors and doors of sapphire.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r8',
    category: 'R',
    name: 'Gandhara',
    points: 2,
    ruler: 'Duryodhana',
    rulerId: 'duryodhana',
    rulerName: 'Duryodhana',
    symbol: '🏔️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The rugged mountain kingdom beyond the Indus, ancestral domain of Queen Gandhari and King Subala, renowned for skilled horsemen and strategic passes.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c9',
    category: 'C',
    name: 'Draupadi',
    points: 8,
    ruler: 'Draupadi',
    rulerId: 'draupadi',
    rulerName: 'Draupadi',
    symbol: '🪷',
    immediateFather: 'Drupada (Father)',
    immediateSon: 'Upapandavas (Sons)',
    detail: 'The queen born from the sacrificial altar whose blazing spirit and relentless pursuit of justice catalyzed the righteous struggle to restore Dharma across Aryavarta.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l9',
    category: 'L',
    name: 'Draupadi\'s Question in the Sabha — Draupadi',
    points: 6,
    ruler: 'Draupadi',
    rulerId: 'draupadi',
    rulerName: 'Draupadi',
    symbol: '❓',
    immediateFather: null,
    immediateSon: null,
    detail: 'Her immortal philosophical interrogation to Bhishma, Drona, and Dhritarashtra in the dice assembly: \'Did Yudhishthira lose himself first, or did he wager me?\'',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm9',
    category: 'M',
    name: 'Virata\'s Court',
    points: 4,
    ruler: 'Draupadi',
    rulerId: 'draupadi',
    rulerName: 'Draupadi',
    symbol: '🏛️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The royal court of Matsya where Draupadi served disguised as Sairandhri alongside the Pandavas during their harrowing final year of incognito exile (Agyatavasa).',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r9',
    category: 'R',
    name: 'Matsya Kingdom',
    points: 2,
    ruler: 'Draupadi',
    rulerId: 'draupadi',
    rulerName: 'Draupadi',
    symbol: '🐟',
    immediateFather: null,
    immediateSon: null,
    detail: 'The verdant pastoral kingdom governed by King Virata, celebrated for vast cattle herds, lakeside pavilions, and secret haven of the Pandavas.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'sp1a',
    category: 'Rival',
    name: 'Shakuni — Dyuta / Dice of Fate',
    points: 0,
    symbol: '🎲',
    detail: 'The master strategist of the loaded dice (Dyuta) crafted from the bones of his ancestors, manipulating the game of chance to seize the fortunes of the realm and steal all accumulated points from the Pot.',
    historicalContext: 'The master strategist of the loaded dice (Dyuta) crafted from the bones of his ancestors, manipulating the game of chance to seize the fortunes of the realm and steal all accumulated points from the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp1b',
    category: 'Rival',
    name: 'Shakuni — Dyuta / Dice of Fate',
    points: 0,
    symbol: '🎲',
    detail: 'The master strategist of the loaded dice (Dyuta) crafted from the bones of his ancestors, manipulating the game of chance to seize the fortunes of the realm and steal all accumulated points from the Pot.',
    historicalContext: 'The master strategist of the loaded dice (Dyuta) crafted from the bones of his ancestors, manipulating the game of chance to seize the fortunes of the realm and steal all accumulated points from the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp1c',
    category: 'Rival',
    name: 'Ashwatthama — Ashwatthama\'s Wrath',
    points: 0,
    symbol: '⚔️',
    detail: 'The immortal warrior son of Drona bearing the celestial gem on his forehead, unleashing nocturnal fury and celestial astras upon the enemy encampment, stealing the full bounty of the Pot.',
    historicalContext: 'The immortal warrior son of Drona bearing the celestial gem on his forehead, unleashing nocturnal fury and celestial astras upon the enemy encampment, stealing the full bounty of the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp1d',
    category: 'Rival',
    name: 'Ashwatthama — Ashwatthama\'s Wrath',
    points: 0,
    symbol: '⚔️',
    detail: 'The immortal warrior son of Drona bearing the celestial gem on his forehead, unleashing nocturnal fury and celestial astras upon the enemy encampment, stealing the full bounty of the Pot.',
    historicalContext: 'The immortal warrior son of Drona bearing the celestial gem on his forehead, unleashing nocturnal fury and celestial astras upon the enemy encampment, stealing the full bounty of the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp2a',
    category: 'Special',
    name: 'Krishna\'s Aadesh',
    points: 0,
    symbol: '📜',
    detail: 'Divine Mandate of Lord Krishna. When played, the player commands a category (Creator, Dharma, Marvel, or Region). The next player MUST play a matching category card or play another Wild.',
    historicalContext: 'Divine Mandate of Lord Krishna. When played, the player commands a category (Creator, Dharma, Marvel, or Region). The next player MUST play a matching category card or play another Wild.',
    variant: 'aadesh',
    type: 'aadesh',
    effect: 'command_category'
  },
  {
    id: 'sp2b',
    category: 'Special',
    name: 'Krishna\'s Aadesh',
    points: 0,
    symbol: '📜',
    detail: 'Divine Mandate of Lord Krishna. When played, the player commands a category (Creator, Dharma, Marvel, or Region). The next player MUST play a matching category card or play another Wild.',
    historicalContext: 'Divine Mandate of Lord Krishna. When played, the player commands a category (Creator, Dharma, Marvel, or Region). The next player MUST play a matching category card or play another Wild.',
    variant: 'aadesh',
    type: 'aadesh',
    effect: 'command_category'
  },
  {
    id: 'sp3a',
    category: 'Special',
    name: 'Mauna Vrat',
    points: 0,
    symbol: '🤫',
    detail: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp3b',
    category: 'Special',
    name: 'Mauna Vrat',
    points: 0,
    symbol: '🤫',
    detail: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp3c',
    category: 'Special',
    name: 'Mauna Vrat',
    points: 0,
    symbol: '🤫',
    detail: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp3d',
    category: 'Special',
    name: 'Mauna Vrat',
    points: 0,
    symbol: '🤫',
    detail: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'The sacred vow of silence (Mauna). Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp4a',
    category: 'Special',
    name: 'Chakravyuha',
    points: 0,
    symbol: '🌀',
    detail: 'The formidable seven-tiered circular military formation devised by Drona. Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    historicalContext: 'The formidable seven-tiered circular military formation devised by Drona. Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    variant: 'chakravyuha',
    type: 'chakravyuha',
    effect: 'reverse_order'
  },
  {
    id: 'sp4b',
    category: 'Special',
    name: 'Chakravyuha',
    points: 0,
    symbol: '🌀',
    detail: 'The formidable seven-tiered circular military formation devised by Drona. Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    historicalContext: 'The formidable seven-tiered circular military formation devised by Drona. Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    variant: 'chakravyuha',
    type: 'chakravyuha',
    effect: 'reverse_order'
  },
  {
    id: 'sp5a',
    category: 'Special',
    name: 'Lakshagriha — House of Lac',
    points: 0,
    symbol: '🔥',
    detail: 'Crisis: The treacherous flammable palace of lacquer in Varnavata ignited in the dead of night! Forces the next player to escape by playing a Region (R) card, or draw a penalty card and lose 1 point.',
    historicalContext: 'Crisis: The treacherous flammable palace of lacquer in Varnavata ignited in the dead of night! Forces the next player to escape by playing a Region (R) card, or draw a penalty card and lose 1 point.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_region'
  },
  {
    id: 'sp5b',
    category: 'Special',
    name: 'Lakshagriha — House of Lac',
    points: 0,
    symbol: '🔥',
    detail: 'Crisis: The treacherous flammable palace of lacquer in Varnavata ignited in the dead of night! Forces the next player to escape by playing a Region (R) card, or draw a penalty card and lose 1 point.',
    historicalContext: 'Crisis: The treacherous flammable palace of lacquer in Varnavata ignited in the dead of night! Forces the next player to escape by playing a Region (R) card, or draw a penalty card and lose 1 point.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_region'
  },
  {
    id: 'sp5c',
    category: 'Special',
    name: 'Kurukshetra — Great War',
    points: 0,
    symbol: '☠️',
    detail: 'Crisis: The cosmic eighteen-day war at Kurukshetra erupts with devastating astras! Forces the next player to deploy a divine weapon / Marvel (M) card, or draw a penalty card and lose 1 point.',
    historicalContext: 'Crisis: The cosmic eighteen-day war at Kurukshetra erupts with devastating astras! Forces the next player to deploy a divine weapon / Marvel (M) card, or draw a penalty card and lose 1 point.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_marvel'
  },
  {
    id: 'sp5d',
    category: 'Special',
    name: 'Kurukshetra — Great War',
    points: 0,
    symbol: '☠️',
    detail: 'Crisis: The cosmic eighteen-day war at Kurukshetra erupts with devastating astras! Forces the next player to deploy a divine weapon / Marvel (M) card, or draw a penalty card and lose 1 point.',
    historicalContext: 'Crisis: The cosmic eighteen-day war at Kurukshetra erupts with devastating astras! Forces the next player to deploy a divine weapon / Marvel (M) card, or draw a penalty card and lose 1 point.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_marvel'
  },
];
