import { CardData } from './types';

export const OFFICIAL_52_CARDS: CardData[] = [
  // 1. Mangal Pandey
  {
    id: 'c1',
    category: 'C',
    name: 'Mangal Pandey',
    points: 8,
    ruler: 'Mangal Pandey',
    rulerId: 'mangal_pandey',
    rulerName: 'Mangal Pandey',
    symbol: '🇮🇳',
    immediateFather: null,
    immediateSon: '1857 Uprising Vanguard',
    detail: 'Sepoy of the 34th Bengal Native Infantry whose defiant stand at Barrackpore on March 29, 1857 ignited the First War of Indian Independence.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l1',
    category: 'L',
    name: 'Barrackpore Revolt of 1857',
    points: 6,
    ruler: 'Mangal Pandey',
    rulerId: 'mangal_pandey',
    rulerName: 'Mangal Pandey',
    symbol: '✊',
    immediateFather: null,
    immediateSon: null,
    detail: 'The historic rebellion on the parade ground of Barrackpore in March 1857, sounding the bugle of national defiance against colonial rule.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm1',
    category: 'M',
    name: 'Barrackpore Uprising',
    points: 4,
    ruler: 'Mangal Pandey',
    rulerId: 'mangal_pandey',
    rulerName: 'Mangal Pandey',
    symbol: '🔥',
    immediateFather: null,
    immediateSon: null,
    detail: 'The spark of heroic resistance that shattered the myth of colonial invincibility and inspired freedom fighters across the subcontinent.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r1',
    category: 'R',
    name: 'Barrackpore',
    points: 2,
    ruler: 'Mangal Pandey',
    rulerId: 'mangal_pandey',
    rulerName: 'Mangal Pandey',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Cantonment town along the sacred Hooghly River in Bengal where Sepoy Mangal Pandey fired the first shot of the 1857 Indian rebellion.',
    variant: 'normal',
    type: 'main'
  },

  // 2. Rani Lakshmibai
  {
    id: 'c2',
    category: 'C',
    name: 'Rani Lakshmibai',
    points: 8,
    ruler: 'Rani Lakshmibai',
    rulerId: 'rani_lakshmibai',
    rulerName: 'Rani Lakshmibai',
    symbol: '⚔️',
    immediateFather: null,
    immediateSon: 'Damodar Rao (Adopted)',
    detail: 'The fearless Queen of Jhansi who rode into battle with sword in hand, leading her soldiers against British annexation forces in 1857.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l2',
    category: 'L',
    name: 'Revolt of Jhansi',
    points: 6,
    ruler: 'Rani Lakshmibai',
    rulerId: 'rani_lakshmibai',
    rulerName: 'Rani Lakshmibai',
    symbol: '🛡️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The steadfast resistance of Jhansi rejecting the Doctrine of Lapse, declaring sovereignty with the immortal cry: "I shall not give up my Jhansi!"',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm2',
    category: 'M',
    name: 'Defence of Jhansi',
    points: 4,
    ruler: 'Rani Lakshmibai',
    rulerId: 'rani_lakshmibai',
    rulerName: 'Rani Lakshmibai',
    symbol: '🏰',
    immediateFather: null,
    immediateSon: null,
    detail: 'The heroic multi-week defence of the Jhansi fort walls and cavalry sallies against overwhelming British siege forces.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r2',
    category: 'R',
    name: 'Jhansi',
    points: 2,
    ruler: 'Rani Lakshmibai',
    rulerId: 'rani_lakshmibai',
    rulerName: 'Rani Lakshmibai',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Historic fort city in Bundelkhand whose majestic citadel and granite ramparts stood as an unbreakable bulwark of national freedom.',
    variant: 'normal',
    type: 'main'
  },

  // 3. Bal Gangadhar Tilak
  {
    id: 'c3',
    category: 'C',
    name: 'Bal Gangadhar Tilak',
    points: 8,
    ruler: 'Bal Gangadhar Tilak',
    rulerId: 'bal_gangadhar_tilak',
    rulerName: 'Bal Gangadhar Tilak',
    symbol: '📜',
    immediateFather: null,
    immediateSon: 'Lal-Bal-Pal Trio',
    detail: 'Lokmanya Tilak, architect of mass Indian nationalism who proclaimed: "Swaraj is my birthright and I shall have it!"',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l3',
    category: 'L',
    name: 'Swaraj Movement',
    points: 6,
    ruler: 'Bal Gangadhar Tilak',
    rulerId: 'bal_gangadhar_tilak',
    rulerName: 'Bal Gangadhar Tilak',
    symbol: '⚡',
    immediateFather: null,
    immediateSon: null,
    detail: 'The nationwide movement demanding complete self-rule (Swaraj), Swadeshi economic boycott, and national education.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm3',
    category: 'M',
    name: 'Kesari Newspaper',
    points: 4,
    ruler: 'Bal Gangadhar Tilak',
    rulerId: 'bal_gangadhar_tilak',
    rulerName: 'Bal Gangadhar Tilak',
    symbol: '📰',
    immediateFather: null,
    immediateSon: null,
    detail: 'The pioneering nationalist Marathi journal founded in 1881 that fearlessly exposed colonial tyranny and rallied millions to the freedom banner.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r3',
    category: 'R',
    name: 'Pune',
    points: 2,
    ruler: 'Bal Gangadhar Tilak',
    rulerId: 'bal_gangadhar_tilak',
    rulerName: 'Bal Gangadhar Tilak',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Cultural heart of Maharashtra where Lokmanya Tilak established Kesari, Deccan Education Society, and mass patriotic community celebrations.',
    variant: 'normal',
    type: 'main'
  },

  // 4. Lala Lajpat Rai
  {
    id: 'c4',
    category: 'C',
    name: 'Lala Lajpat Rai',
    points: 8,
    ruler: 'Lala Lajpat Rai',
    rulerId: 'lala_lajpat_rai',
    rulerName: 'Lala Lajpat Rai',
    symbol: '🦁',
    immediateFather: null,
    immediateSon: 'Punjab Kesari Vanguard',
    detail: 'Punjab Kesari (The Lion of Punjab), fearless member of Lal-Bal-Pal who led mass protests against British commissions and colonial oppression.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l4',
    category: 'L',
    name: 'Punjab Nationalist Movement',
    points: 6,
    ruler: 'Lala Lajpat Rai',
    rulerId: 'lala_lajpat_rai',
    rulerName: 'Lala Lajpat Rai',
    symbol: '🚩',
    immediateFather: null,
    immediateSon: null,
    detail: 'Grassroots nationalist mobilization across Punjab demanding agrarian justice, civil rights, and complete liberation from colonial subjugation.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm4',
    category: 'M',
    name: 'Servants of the People Society',
    points: 4,
    ruler: 'Lala Lajpat Rai',
    rulerId: 'lala_lajpat_rai',
    rulerName: 'Lala Lajpat Rai',
    symbol: '🤝',
    immediateFather: null,
    immediateSon: null,
    detail: 'The legendary national society inaugurated in Lahore in 1921 to enlist and train selfless patriotic youth for national public service.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r4',
    category: 'R',
    name: 'Amritsar',
    points: 2,
    ruler: 'Lala Lajpat Rai',
    rulerId: 'lala_lajpat_rai',
    rulerName: 'Lala Lajpat Rai',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'The historic city of Punjab, epicenter of fierce political activism, congress sessions, and steadfast resistance against imperial exploitation.',
    variant: 'normal',
    type: 'main'
  },

  // 5. Mahatma Gandhi
  {
    id: 'c5',
    category: 'C',
    name: 'Mahatma Gandhi',
    points: 8,
    ruler: 'Mahatma Gandhi',
    rulerId: 'mahatma_gandhi',
    rulerName: 'Mahatma Gandhi',
    symbol: '🕊️',
    immediateFather: null,
    immediateSon: 'Father of the Nation',
    detail: 'Father of the Nation who mobilized millions through non-violent Satyagraha, pioneering the Dandi Salt March and Quit India movement.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l5',
    category: 'L',
    name: 'Satyagraha Movement',
    points: 6,
    ruler: 'Mahatma Gandhi',
    rulerId: 'mahatma_gandhi',
    rulerName: 'Mahatma Gandhi',
    symbol: '⚖️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The philosophy and weapon of non-violent civil resistance, truth, and moral courage that challenged the might of the British Empire.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm5',
    category: 'M',
    name: 'Charkha & Khadi',
    points: 4,
    ruler: 'Mahatma Gandhi',
    rulerId: 'mahatma_gandhi',
    rulerName: 'Mahatma Gandhi',
    symbol: '☸️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The humble wooden spinning wheel and handspun cloth that became the national emblem of self-reliance, unity, and economic independence.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r5',
    category: 'R',
    name: 'Sabarmati Ashram',
    points: 2,
    ruler: 'Mahatma Gandhi',
    rulerId: 'mahatma_gandhi',
    rulerName: 'Mahatma Gandhi',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Gandhi\'s historic riverside sanctuary in Ahmedabad, nerve center of Satyagraha planning and starting point of the historic 1930 Dandi March.',
    variant: 'normal',
    type: 'main'
  },

  // 6. Sardar Vallabhbhai Patel
  {
    id: 'c6',
    category: 'C',
    name: 'Sardar Vallabhbhai Patel',
    points: 8,
    ruler: 'Sardar Vallabhbhai Patel',
    rulerId: 'sardar_patel',
    rulerName: 'Sardar Vallabhbhai Patel',
    symbol: '🛡️',
    immediateFather: null,
    immediateSon: 'Iron Man of India',
    detail: 'The Iron Man of India whose visionary statesmanship and iron will integrated over 560 princely states into the sovereign Republic of India.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l6',
    category: 'L',
    name: 'Bardoli Satyagraha',
    points: 6,
    ruler: 'Sardar Vallabhbhai Patel',
    rulerId: 'sardar_patel',
    rulerName: 'Sardar Vallabhbhai Patel',
    symbol: '🌾',
    immediateFather: null,
    immediateSon: null,
    detail: 'The triumphant peasant non-tax campaign of 1928 that defeated colonial tax extortion and earned Vallabhbhai the revered title of "Sardar".',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm6',
    category: 'M',
    name: 'Kheda & Bardoli Leadership',
    points: 4,
    ruler: 'Sardar Vallabhbhai Patel',
    rulerId: 'sardar_patel',
    rulerName: 'Sardar Vallabhbhai Patel',
    symbol: '🏛️',
    immediateFather: null,
    immediateSon: null,
    detail: 'Masterful grassroots organizational discipline that empowered farmers, unified communities, and compelled colonial authorities to yield.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r6',
    category: 'R',
    name: 'Bardoli',
    points: 2,
    ruler: 'Sardar Vallabhbhai Patel',
    rulerId: 'sardar_patel',
    rulerName: 'Sardar Vallabhbhai Patel',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Rural heartland in Gujarat that became the crucible of peasant solidarity, non-violent discipline, and Patel\'s legendary leadership.',
    variant: 'normal',
    type: 'main'
  },

  // 7. Bhagat Singh
  {
    id: 'c7',
    category: 'C',
    name: 'Bhagat Singh',
    points: 8,
    ruler: 'Bhagat Singh',
    rulerId: 'bhagat_singh',
    rulerName: 'Bhagat Singh',
    symbol: '⭐',
    immediateFather: null,
    immediateSon: 'HSRA Revolutionary Vanguard',
    detail: 'Shaheed Bhagat Singh, intellectual and fearless socialist revolutionary whose supreme sacrifice and cry of "Inquilab Zindabad" electrified India.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l7',
    category: 'L',
    name: 'Inquilab Movement',
    points: 6,
    ruler: 'Bhagat Singh',
    rulerId: 'bhagat_singh',
    rulerName: 'Bhagat Singh',
    symbol: '🔥',
    immediateFather: null,
    immediateSon: null,
    detail: 'The clarion call of revolution aimed at overthrowing foreign imperialism and eradicating exploitation to establish a just, sovereign socialist republic.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm7',
    category: 'M',
    name: 'Hindustan Socialist Republican Association (HSRA)',
    points: 4,
    ruler: 'Bhagat Singh',
    rulerId: 'bhagat_singh',
    rulerName: 'Bhagat Singh',
    symbol: '🚩',
    immediateFather: null,
    immediateSon: null,
    detail: 'The militant revolutionary vanguard reorganized in 1928, dedicated to armed resistance against colonial rule and the emancipation of the masses.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r7',
    category: 'R',
    name: 'Feroz Shah Kotla, Delhi',
    points: 2,
    ruler: 'Bhagat Singh',
    rulerId: 'bhagat_singh',
    rulerName: 'Bhagat Singh',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Ancient ruins of Delhi fortress where Bhagat Singh, Azad, and fellow revolutionaries convened in September 1928 to resolve on socialist revolution.',
    variant: 'normal',
    type: 'main'
  },

  // 8. Chandrashekhar Azad
  {
    id: 'c8',
    category: 'C',
    name: 'Chandrashekhar Azad',
    points: 8,
    ruler: 'Chandrashekhar Azad',
    rulerId: 'chandrashekhar_azad',
    rulerName: 'Chandrashekhar Azad',
    symbol: '🎯',
    immediateFather: null,
    immediateSon: 'Commander of Freedom',
    detail: 'Legendary Commander-in-Chief of the HSRA who defied colonial police with the vow: "Dushman ki goliyon ka hum samna karenge, Azad hi rahe hain, Azad hi rahenge!"',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l8',
    category: 'L',
    name: 'Hindustan Revolutionary Movement',
    points: 6,
    ruler: 'Chandrashekhar Azad',
    rulerId: 'chandrashekhar_azad',
    rulerName: 'Chandrashekhar Azad',
    symbol: '⚡',
    immediateFather: null,
    immediateSon: null,
    detail: 'The underground armed resistance network that struck strategic blows against British tyranny and inspired unconditional patriotism.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm8',
    category: 'M',
    name: 'Hindustan Republican Association (HRA)',
    points: 4,
    ruler: 'Chandrashekhar Azad',
    rulerId: 'chandrashekhar_azad',
    rulerName: 'Chandrashekhar Azad',
    symbol: '⚔️',
    immediateFather: null,
    immediateSon: null,
    detail: 'The resolute revolutionary organization formed to federate freedom fighters across North India in coordinated defense of the nation.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r8',
    category: 'R',
    name: 'Alfred Park, Allahabad',
    points: 2,
    ruler: 'Chandrashekhar Azad',
    rulerId: 'chandrashekhar_azad',
    rulerName: 'Chandrashekhar Azad',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'Historic park in Prayagraj where Azad fought alone against surrounded colonial police forces, upholding his vow to remain forever Azad.',
    variant: 'normal',
    type: 'main'
  },

  // 9. Subhas Chandra Bose
  {
    id: 'c9',
    category: 'C',
    name: 'Subhas Chandra Bose',
    points: 8,
    ruler: 'Subhas Chandra Bose',
    rulerId: 'subhas_chandra_bose',
    rulerName: 'Subhas Chandra Bose',
    symbol: '🎖️',
    immediateFather: null,
    immediateSon: 'Netaji · Azad Hind Fauj',
    detail: 'Netaji, supreme commander of the Indian National Army who rallied the nation with: "Give me blood, and I shall give you freedom!"',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'l9',
    category: 'L',
    name: 'Azad Hind Movement',
    points: 6,
    ruler: 'Subhas Chandra Bose',
    rulerId: 'subhas_chandra_bose',
    rulerName: 'Subhas Chandra Bose',
    symbol: '🌅',
    immediateFather: null,
    immediateSon: null,
    detail: 'The Provisional Government of Free India established in 1943, creating its own military, currency, and administration to liberate the motherland.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'm9',
    category: 'M',
    name: 'Indian National Army (INA)',
    points: 4,
    ruler: 'Subhas Chandra Bose',
    rulerId: 'subhas_chandra_bose',
    rulerName: 'Subhas Chandra Bose',
    symbol: '🐅',
    immediateFather: null,
    immediateSon: null,
    detail: 'The heroic Azad Hind Fauj with its brave soldiers and Rani of Jhansi Regiment that fought valiantly on the northeastern frontier for India\'s independence.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r9',
    category: 'R',
    name: 'Singapore',
    points: 2,
    ruler: 'Subhas Chandra Bose',
    rulerId: 'subhas_chandra_bose',
    rulerName: 'Subhas Chandra Bose',
    symbol: '📍',
    immediateFather: null,
    immediateSon: null,
    detail: 'The historic Southeast Asian hub where Netaji took command of the INA, proclaimed the Azad Hind Government, and sounded the call of "Dilli Chalo!".',
    variant: 'normal',
    type: 'main'
  },

  // 10. SPECIAL CARDS (16 Cards)
  // Rival / Wild + Steal (4 cards: 2x Godse, 2x Mountbatten)
  {
    id: 'sp1a',
    category: 'Rival',
    name: 'Nathuram Godse — The Assassin',
    points: 0,
    symbol: '⚔️',
    detail: 'Historical Antagonist / Epilogue: The assassin who took the life of Mahatma Gandhi. Not a freedom fighter. Steals all accumulated points from the Pot.',
    historicalContext: 'Historical Antagonist / Epilogue: The assassin who took the life of Mahatma Gandhi. Not a freedom fighter. Steals all accumulated points from the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp1b',
    category: 'Rival',
    name: 'Nathuram Godse — The Assassin',
    points: 0,
    symbol: '⚔️',
    detail: 'Historical Antagonist / Epilogue: The assassin who took the life of Mahatma Gandhi. Not a freedom fighter. Steals all accumulated points from the Pot.',
    historicalContext: 'Historical Antagonist / Epilogue: The assassin who took the life of Mahatma Gandhi. Not a freedom fighter. Steals all accumulated points from the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp1c',
    category: 'Rival',
    name: 'Lord Mountbatten — The Last Viceroy',
    points: 0,
    symbol: '👑',
    detail: 'Colonial Authority: The last British Viceroy who presided over the turbulent partition and transfer of power. Steals all accumulated points from the Pot.',
    historicalContext: 'Colonial Authority: The last British Viceroy who presided over the turbulent partition and transfer of power. Steals all accumulated points from the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },
  {
    id: 'sp1d',
    category: 'Rival',
    name: 'Lord Mountbatten — The Last Viceroy',
    points: 0,
    symbol: '👑',
    detail: 'Colonial Authority: The last British Viceroy who presided over the turbulent partition and transfer of power. Steals all accumulated points from the Pot.',
    historicalContext: 'Colonial Authority: The last British Viceroy who presided over the turbulent partition and transfer of power. Steals all accumulated points from the Pot.',
    variant: 'rival',
    type: 'rival',
    effect: 'steal_pot'
  },

  // Aadesh / Rare Wild (2 cards)
  {
    id: 'sp2a',
    category: 'Special',
    name: "Gandhi's Aadesh — Do or Die",
    points: 0,
    symbol: '📜',
    detail: 'Historic Command: The famous August 1942 mandate of "Karo ya Maro" (Do or Die). The player commands a category (Leader, Movement, Contribution, or Historical Place). The next player MUST play a matching card or Wild.',
    historicalContext: 'Historic Command: The famous August 1942 mandate of "Karo ya Maro" (Do or Die). The player commands a category (Leader, Movement, Contribution, or Historical Place). The next player MUST play a matching card or Wild.',
    variant: 'aadesh',
    type: 'aadesh',
    effect: 'command_category'
  },
  {
    id: 'sp2b',
    category: 'Special',
    name: "Gandhi's Aadesh — Do or Die",
    points: 0,
    symbol: '📜',
    detail: 'Historic Command: The famous August 1942 mandate of "Karo ya Maro" (Do or Die). The player commands a category (Leader, Movement, Contribution, or Historical Place). The next player MUST play a matching card or Wild.',
    historicalContext: 'Historic Command: The famous August 1942 mandate of "Karo ya Maro" (Do or Die). The player commands a category (Leader, Movement, Contribution, or Historical Place). The next player MUST play a matching card or Wild.',
    variant: 'aadesh',
    type: 'aadesh',
    effect: 'command_category'
  },

  // Mouna / Skip (4 cards)
  {
    id: 'sp3a',
    category: 'Special',
    name: 'Silent Protest',
    points: 0,
    symbol: '🤫',
    detail: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp3b',
    category: 'Special',
    name: 'Silent Protest',
    points: 0,
    symbol: '🤫',
    detail: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp3c',
    category: 'Special',
    name: 'Silent Protest',
    points: 0,
    symbol: '🤫',
    detail: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },
  {
    id: 'sp3d',
    category: 'Special',
    name: 'Silent Protest',
    points: 0,
    symbol: '🤫',
    detail: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    historicalContext: 'Silent Protest: A disciplined non-violent Hartal and peaceful silence. Forces the next player to lose their turn completely, draw 1 card from the deck, and suffer a 1-point penalty.',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next'
  },

  // Chakravyuha / Reverse (2 cards)
  {
    id: 'sp4a',
    category: 'Special',
    name: 'Revolutionary Turn',
    points: 0,
    symbol: '🌀',
    detail: 'Revolutionary Turn: A dramatic shift in the political tide! Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    historicalContext: 'Revolutionary Turn: A dramatic shift in the political tide! Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    variant: 'chakravyuha',
    type: 'chakravyuha',
    effect: 'reverse_order'
  },
  {
    id: 'sp4b',
    category: 'Special',
    name: 'Revolutionary Turn',
    points: 0,
    symbol: '🌀',
    detail: 'Revolutionary Turn: A dramatic shift in the political tide! Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    historicalContext: 'Revolutionary Turn: A dramatic shift in the political tide! Instantly reverses the flow of play (clockwise becomes anticlockwise).',
    variant: 'chakravyuha',
    type: 'chakravyuha',
    effect: 'reverse_order'
  },

  // Crisis Cards (4 cards: 2x Jallianwala Bagh, 2x Colonial Repression)
  {
    id: 'sp5a',
    category: 'Special',
    name: 'Jallianwala Bagh Crisis',
    points: 0,
    symbol: '🛑',
    detail: 'Crisis: The tragic massacre at Amritsar on Baisakhi 1919 shook India! Forces the next player to respond by playing an R (Historical Place) card or a Wild card.',
    historicalContext: 'Crisis: The tragic massacre at Amritsar on Baisakhi 1919 shook India! Forces the next player to respond by playing an R (Historical Place) card or a Wild card.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_region'
  },
  {
    id: 'sp5b',
    category: 'Special',
    name: 'Jallianwala Bagh Crisis',
    points: 0,
    symbol: '🛑',
    detail: 'Crisis: The tragic massacre at Amritsar on Baisakhi 1919 shook India! Forces the next player to respond by playing an R (Historical Place) card or a Wild card.',
    historicalContext: 'Crisis: The tragic massacre at Amritsar on Baisakhi 1919 shook India! Forces the next player to respond by playing an R (Historical Place) card or a Wild card.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_region'
  },
  {
    id: 'sp5c',
    category: 'Special',
    name: 'Colonial Repression',
    points: 0,
    symbol: '⛓️',
    detail: 'Crisis: Draconian colonial crackdowns, lathi charges, and repressive ordinances sweep the nation! Forces the next player to respond by playing an Le (Movement / Ideology) card or a Wild card.',
    historicalContext: 'Crisis: Draconian colonial crackdowns, lathi charges, and repressive ordinances sweep the nation! Forces the next player to respond by playing an Le (Movement / Ideology) card or a Wild card.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_movement'
  },
  {
    id: 'sp5d',
    category: 'Special',
    name: 'Colonial Repression',
    points: 0,
    symbol: '⛓️',
    detail: 'Crisis: Draconian colonial crackdowns, lathi charges, and repressive ordinances sweep the nation! Forces the next player to respond by playing an Le (Movement / Ideology) card or a Wild card.',
    historicalContext: 'Crisis: Draconian colonial crackdowns, lathi charges, and repressive ordinances sweep the nation! Forces the next player to respond by playing an Le (Movement / Ideology) card or a Wild card.',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_movement'
  }
];
