import { CardData } from './types';

export const OFFICIAL_52_CARDS: CardData[] = [
  {
    id: 'c1',
    category: 'C',
    name: 'Babur',
    points: 8,
    ruler: 'Babur',
    rulerId: 'babur',
    rulerName: 'Babur',
    symbol: '👑',
    immediateFather: null,
    immediateSon: 'Humayun',
    detail: 'The founder of the Mughal Empire. Descendant of Timur and Genghis Khan, he defeated Ibrahim Lodi at the First Battle of Panipat (1526) using superior artillery tactics.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c2',
    category: 'C',
    name: 'Humayun',
    points: 8,
    ruler: 'Humayun',
    rulerId: 'humayun',
    rulerName: 'Humayun',
    symbol: '👑',
    immediateFather: 'Babur',
    immediateSon: 'Akbar',
    detail: "Babur's eldest son. Lost the empire to Sher Shah Suri, fled to Persia, and returned to reclaim the throne in 1555 — only to die from a staircase fall a year later.",
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c3',
    category: 'C',
    name: 'Akbar',
    points: 8,
    ruler: 'Akbar',
    rulerId: 'akbar',
    rulerName: 'Akbar',
    symbol: '👑',
    immediateFather: 'Humayun',
    immediateSon: 'Jahangir',
    detail: 'The greatest Mughal emperor. Unified the subcontinent, abolished Jizya, built the Mansabdari system, founded Din-i-Ilahi, and ruled for 49 years with unmatched tolerance.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c4',
    category: 'C',
    name: 'Jahangir',
    points: 8,
    ruler: 'Jahangir',
    rulerId: 'jahangir',
    rulerName: 'Jahangir',
    symbol: '👑',
    immediateFather: 'Akbar',
    immediateSon: 'Shah Jahan',
    detail: 'The connoisseur emperor. Patron of the finest Mughal miniature paintings, lover of Kashmir, and author of the Tuzuk-i-Jahangiri — his celebrated memoirs.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c5',
    category: 'C',
    name: 'Shah Jahan',
    points: 8,
    ruler: 'Shah Jahan',
    rulerId: 'shah_jahan',
    rulerName: 'Shah Jahan',
    symbol: '👑',
    immediateFather: 'Jahangir',
    immediateSon: 'Aurangzeb',
    detail: 'Builder of the Taj Mahal and the Peacock Throne. His reign is the pinnacle of Mughal architecture. He was imprisoned by his own son Aurangzeb in Agra Fort until his death.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c6',
    category: 'C',
    name: 'Aurangzeb',
    points: 8,
    ruler: 'Aurangzeb',
    rulerId: 'aurangzeb',
    rulerName: 'Aurangzeb',
    symbol: '👑',
    immediateFather: 'Shah Jahan',
    immediateSon: 'Bahadur Shah I',
    detail: 'The last great Mughal. Ruled for 49 years, expanded the empire to its greatest territorial extent, but his rigid policies and the 27-year Deccan campaign accelerated the empire\'s decline.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c7',
    category: 'C',
    name: 'Bahadur Shah I',
    points: 8,
    ruler: 'Bahadur Shah I',
    rulerId: 'bahadur_shah_i',
    rulerName: 'Bahadur Shah I',
    symbol: '👑',
    immediateFather: 'Aurangzeb',
    immediateSon: 'Muhammad Shah',
    detail: 'Also known as Shah Alam I. Reversed many of Aurangzeb\'s divisive policies, sought reconciliation with the Rajputs and Sikhs, and tried to stabilize a fractured empire.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c8',
    category: 'C',
    name: 'Muhammad Shah',
    points: 8,
    ruler: 'Muhammad Shah',
    rulerId: 'muhammad_shah',
    rulerName: 'Muhammad Shah',
    symbol: '👑',
    immediateFather: 'Bahadur Shah I',
    immediateSon: 'Bahadur Shah Zafar',
    detail: 'Known as \'Rangila\' (the Colorful). A patron of arts and music who presided over the catastrophic sack of Delhi by Nadir Shah in 1739, losing the Peacock Throne and Koh-i-Noor.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'c9',
    category: 'C',
    name: 'Bahadur Shah Zafar',
    points: 8,
    ruler: 'Bahadur Shah Zafar',
    rulerId: 'bahadur_shah_zafar',
    rulerName: 'Bahadur Shah Zafar',
    symbol: '👑',
    immediateFather: 'Muhammad Shah',
    immediateSon: null,
    detail: 'The last Mughal Emperor and a celebrated Urdu poet. Became the nominal figurehead of the 1857 Uprising. Exiled to Rangoon, where he died in 1862 — far from Delhi he loved.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le1',
    category: 'Le',
    name: 'Matchlock Artillery Reforms',
    points: 6,
    ruler: 'Babur',
    rulerId: 'babur',
    rulerName: 'Babur',
    symbol: '⚖️',
    detail: 'Introduced Ottoman-style cannons and matchlock muskets at Panipat (1526). The first use of firearms by a Mughal army — it shattered the traditional war elephant strategies of Lodi forces.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le2',
    category: 'Le',
    name: 'Persian Safavid Protocol',
    points: 6,
    ruler: 'Humayun',
    rulerId: 'humayun',
    rulerName: 'Humayun',
    symbol: '⚖️',
    detail: 'Adopted Persian court etiquette, dress, and astronomy during his exile at the Safavid court. Transformed Mughal court culture permanently with Persian aesthetic sensibilities.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le3',
    category: 'Le',
    name: 'Mansabdari System & Ibadat Khana',
    points: 6,
    ruler: 'Akbar',
    rulerId: 'akbar',
    rulerName: 'Akbar',
    symbol: '⚖️',
    detail: 'Rank-based military system (10–5,000 troops) that standardized the imperial army. Combined with the Ibadat Khana — an interfaith debate hall where scholars of all religions gathered.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le4',
    category: 'Le',
    name: 'Zanjir-i-Adal (Chain of Justice)',
    points: 6,
    ruler: 'Jahangir',
    rulerId: 'jahangir',
    rulerName: 'Jahangir',
    symbol: '⚖️',
    detail: 'A 60-bell golden chain outside Agra Fort. Any citizen could ring it to petition the Emperor directly for justice. A landmark act of accessible governance in Mughal history.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le5',
    category: 'Le',
    name: 'Peacock Throne Commission',
    points: 6,
    ruler: 'Shah Jahan',
    rulerId: 'shah_jahan',
    rulerName: 'Shah Jahan',
    symbol: '⚖️',
    detail: 'Cost 2x the Taj Mahal to build. Encrusted with the Koh-i-Noor and countless jewels. The ultimate symbol of Mughal imperial wealth — stolen by Nadir Shah during the 1739 invasion.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le6',
    category: 'Le',
    name: 'Fatawa-e-Alamgiri',
    points: 6,
    ruler: 'Aurangzeb',
    rulerId: 'aurangzeb',
    rulerName: 'Aurangzeb',
    symbol: '⚖️',
    detail: 'The most comprehensive Hanafi Islamic legal code ever compiled. A massive 30-volume legal encyclopaedia codifying Islamic law — assembled by 500 scholars over decades under Aurangzeb\'s direction.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le7',
    category: 'Le',
    name: 'Jizya Abolishment & Rajput Alliance',
    points: 6,
    ruler: 'Bahadur Shah I',
    rulerId: 'bahadur_shah_i',
    rulerName: 'Bahadur Shah I',
    symbol: '⚖️',
    detail: 'Reversed Aurangzeb\'s controversial tax on non-Muslims (Jizya). Actively sought to rebuild alliances with Rajput clans — a conciliatory move to re-stabilize the fractured Mughal coalition.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le8',
    category: 'Le',
    name: 'Khayal & Tappa Music Revival',
    points: 6,
    ruler: 'Muhammad Shah',
    rulerId: 'muhammad_shah',
    rulerName: 'Muhammad Shah',
    symbol: '⚖️',
    detail: 'Patronized Niyamat Khan (Sadarang) and revived Hindustani classical music at court. The Khayal genre flourished under Muhammad Shah\'s reign into its most sophisticated form.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'le9',
    category: 'Le',
    name: 'Last Imperial Firman (1857)',
    points: 6,
    ruler: 'Bahadur Shah Zafar',
    rulerId: 'bahadur_shah_zafar',
    rulerName: 'Bahadur Shah Zafar',
    symbol: '⚖️',
    detail: 'The final royal decree issued by a Mughal Emperor — addressed to rebel sepoys during the 1857 Uprising. A last gasp of imperial authority before the British dissolved the dynasty forever.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma1',
    category: 'Ma',
    name: 'Baburnama (Autobiography)',
    points: 4,
    ruler: 'Babur',
    rulerId: 'babur',
    rulerName: 'Babur',
    symbol: '🏛️',
    itemType: 'Literature',
    detail: 'Babur\'s memoirs in Chagatai Turkic. A rare, candid autobiography of a conqueror — covering his battles, loves, nature observations, and failures with extraordinary honesty and literary flair.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma2',
    category: 'Ma',
    name: 'Din Panah Citadel',
    points: 4,
    ruler: 'Humayun',
    rulerId: 'humayun',
    rulerName: 'Humayun',
    symbol: '🏛️',
    itemType: 'Architecture',
    detail: 'His grand city in Delhi — later destroyed by Sher Shah Suri. Symbol of fragile ambition. The foundations of what would eventually become Old Delhi were first laid here.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma3',
    category: 'Ma',
    name: 'Fatehpur Sikri & Buland Darwaza',
    points: 4,
    ruler: 'Akbar',
    rulerId: 'akbar',
    rulerName: 'Akbar',
    symbol: '🏛️',
    itemType: 'Architecture',
    detail: 'Victory city built to honor Sufi saint Salim Chishti. Buland Darwaza — the world\'s highest gateway at 54 meters — stands as testament to Akbar\'s imperial confidence and architectural ambition.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma4',
    category: 'Ma',
    name: 'Mughal Miniature Painting Patronage',
    points: 4,
    ruler: 'Jahangir',
    rulerId: 'jahangir',
    rulerName: 'Jahangir',
    symbol: '🏛️',
    itemType: 'Art',
    detail: 'Jahangir\'s atelier produced the finest miniature paintings, blending Persian and Indian styles. His discerning eye could identify any painter\'s hand from a single brushstroke.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma5',
    category: 'Ma',
    name: 'Taj Mahal',
    points: 4,
    ruler: 'Shah Jahan',
    rulerId: 'shah_jahan',
    rulerName: 'Shah Jahan',
    symbol: '🏛️',
    itemType: 'Architecture',
    detail: 'Built for Mumtaz Mahal over 22 years by 20,000 artisans. A UNESCO World Heritage Site and one of humanity\'s greatest architectural achievements. The pinnacle of Mughal art.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma6',
    category: 'Ma',
    name: 'Moti Masjid (Delhi)',
    points: 4,
    ruler: 'Aurangzeb',
    rulerId: 'aurangzeb',
    rulerName: 'Aurangzeb',
    symbol: '🏛️',
    itemType: 'Architecture',
    detail: 'The Pearl Mosque inside Red Fort. Built for private royal prayers. A rare marble gem — intimate in scale yet exquisite in craft, a counterpoint to Aurangzeb\'s austere reputation.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma7',
    category: 'Ma',
    name: 'Shahi Qawwali Patronage',
    points: 4,
    ruler: 'Bahadur Shah I',
    rulerId: 'bahadur_shah_i',
    rulerName: 'Bahadur Shah I',
    symbol: '🏛️',
    itemType: 'Art/Music',
    detail: 'Patronized Sufi music and Qawwali at the imperial court. A cultural bridge between faiths — using music as diplomacy at a moment when religious tensions threatened to fracture the empire.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma8',
    category: 'Ma',
    name: 'Rang Mahal Mirror Work',
    points: 4,
    ruler: 'Muhammad Shah',
    rulerId: 'muhammad_shah',
    rulerName: 'Muhammad Shah',
    symbol: '🏛️',
    itemType: 'Art',
    detail: 'The Palace of Colors inside Red Fort. Adorned with mirrors and gold leaf that reflected candlelight into a thousand shards. A testament to Muhammad Shah\'s love of beauty amid political chaos.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'ma9',
    category: 'Ma',
    name: 'Zafar\'s Urdu Poetry',
    points: 4,
    ruler: 'Bahadur Shah Zafar',
    rulerId: 'bahadur_shah_zafar',
    rulerName: 'Bahadur Shah Zafar',
    symbol: '🏛️',
    itemType: 'Literature',
    detail: 'His ghazals are legendary. \'Lagta nahin hai dil mera ujde dayar mein.\' Written in exile, his poetry mourns lost glory with unmatched elegance — among the finest Urdu verse ever composed.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r1',
    category: 'R',
    name: 'Ferghana Valley',
    points: 2,
    ruler: 'Babur',
    rulerId: 'babur',
    rulerName: 'Babur',
    symbol: '🗺️',
    detail: 'Babur\'s ancestral homeland in modern Uzbekistan. The land he lost as a young prince and spent years trying to reclaim. His nostalgia for Ferghana runs through every page of the Baburnama.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r2',
    category: 'R',
    name: 'Kabul-Ghazni Pass',
    points: 2,
    ruler: 'Humayun',
    rulerId: 'humayun',
    rulerName: 'Humayun',
    symbol: '🗺️',
    detail: 'The treacherous mountain route Humayun fled through to reach Persia after his defeat. Key to his survival and eventual return — the escape route that kept the Mughal lineage alive.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r3',
    category: 'R',
    name: 'Gujarat & Bengal Subahs',
    points: 2,
    ruler: 'Akbar',
    rulerId: 'akbar',
    rulerName: 'Akbar',
    symbol: '🗺️',
    detail: 'The richest trade provinces of the empire. Gujarat for coastal ports and maritime trade, Bengal for textiles and agricultural surplus. Together they formed the economic backbone of Mughal wealth.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r4',
    category: 'R',
    name: 'Kashmir Valley',
    points: 2,
    ruler: 'Jahangir',
    rulerId: 'jahangir',
    rulerName: 'Jahangir',
    symbol: '🗺️',
    detail: 'Annexed in 1586. Jahangir called it \'Paradise on Earth\' and visited 13 times. His most beloved territory — he built magnificent gardens there and is said to have wept when he had to leave.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r5',
    category: 'R',
    name: 'Agra & Delhi Subahs',
    points: 2,
    ruler: 'Shah Jahan',
    rulerId: 'shah_jahan',
    rulerName: 'Shah Jahan',
    symbol: '🗺️',
    detail: 'The twin capitals of the golden era. Agra for legacy and the Taj Mahal, Delhi (Shahjahanabad) for the future. Together they represent the zenith of Mughal urban planning and power.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r6',
    category: 'R',
    name: 'Deccan Plateau',
    points: 2,
    ruler: 'Aurangzeb',
    rulerId: 'aurangzeb',
    rulerName: 'Aurangzeb',
    symbol: '🗺️',
    detail: 'Site of the catastrophic 27-year Mughal-Maratha war. Aurangzeb spent the final decades of his reign here, far from Delhi. The campaign drained the imperial treasury and military beyond recovery.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r7',
    category: 'R',
    name: 'Khyber Pass Region',
    points: 2,
    ruler: 'Bahadur Shah I',
    rulerId: 'bahadur_shah_i',
    rulerName: 'Bahadur Shah I',
    symbol: '🗺️',
    detail: 'The strategic Afghan border he struggled to pacify after Aurangzeb\'s exhausting wars. Key to Central Asian trade routes and the perennial battleground of empires since Alexander the Great.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r8',
    category: 'R',
    name: 'Persian Footholds',
    points: 2,
    ruler: 'Muhammad Shah',
    rulerId: 'muhammad_shah',
    rulerName: 'Muhammad Shah',
    symbol: '🗺️',
    detail: 'The western provinces lost to Nadir Shah after the devastating 1739 invasion. Their loss marked the irreversible shrinking of Mughal territorial power and prestige on the world stage.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'r9',
    category: 'R',
    name: 'Rangoon (Exile)',
    points: 2,
    ruler: 'Bahadur Shah Zafar',
    rulerId: 'bahadur_shah_zafar',
    rulerName: 'Bahadur Shah Zafar',
    symbol: '🗺️',
    detail: 'The Burmese prison-city where the last Mughal died in 1862. He never returned to Delhi. On his grave he reportedly wished he had not even four yards of land in his beloved homeland.',
    variant: 'normal',
    type: 'main'
  },
  {
    id: 'sp1a',
    category: 'Special',
    name: 'Shivaji',
    points: 0,
    ruler: null,
    symbol: '⚔️',
    variant: 'rival',
    type: 'rival',
    effect: 'Steals the ENTIRE Table Pot. All accumulated points on the table go to the player who plays this card. Pot resets to 0.',
    detail: 'The Maratha warrior who defeated Mughal generals, established Hindavi Swarajya, and escaped Aurangzeb\'s prison in Agra. He built a navy, codified law, and forged a nation.'
  },
  {
    id: 'sp1b',
    category: 'Special',
    name: 'Shivaji',
    points: 0,
    ruler: null,
    symbol: '⚔️',
    variant: 'rival',
    type: 'rival',
    effect: 'Steals the ENTIRE Table Pot. All accumulated points on the table go to the player who plays this card. Pot resets to 0.',
    detail: 'The Maratha warrior who defeated Mughal generals, established Hindavi Swarajya, and escaped Aurangzeb\'s prison in Agra. He built a navy, codified law, and forged a nation.'
  },
  {
    id: 'sp2a',
    category: 'Special',
    name: 'Maharana Pratap',
    points: 0,
    ruler: null,
    symbol: '🦁',
    variant: 'rival',
    type: 'rival',
    effect: 'Steals the ENTIRE Table Pot. All accumulated points on the table go to the player who plays this card. Pot resets to 0.',
    detail: 'The Rajput king of Mewar who never submitted to Akbar. Fought the Battle of Haldighati (1576) and lived free till his last breath. His horse Chetak is as legendary as the man himself.'
  },
  {
    id: 'sp2b',
    category: 'Special',
    name: 'Maharana Pratap',
    points: 0,
    ruler: null,
    symbol: '🦁',
    variant: 'rival',
    type: 'rival',
    effect: 'Steals the ENTIRE Table Pot. All accumulated points on the table go to the player who plays this card. Pot resets to 0.',
    detail: 'The Rajput king of Mewar who never submitted to Akbar. Fought the Battle of Haldighati (1576) and lived free till his last breath. His horse Chetak is as legendary as the man himself.'
  },
  {
    id: 'sp3a',
    category: 'Special',
    name: 'Aadesh (Command)',
    points: 0,
    ruler: null,
    symbol: '📜',
    variant: 'aadesh',
    type: 'aadesh',
    effect: 'command_category',
    detail: 'Imperial Farman. When played, the sovereign decrees a category (C, L, M, or R). The next player MUST play a card of that category or play another Wild, or draw 1 card and lose 1 point.'
  },
  {
    id: 'sp3b',
    category: 'Special',
    name: 'Aadesh (Command)',
    points: 0,
    ruler: null,
    symbol: '📜',
    variant: 'aadesh',
    type: 'aadesh',
    effect: 'command_category',
    detail: 'Imperial Farman. When played, the sovereign decrees a category (C, L, M, or R). The next player MUST play a card of that category or play another Wild, or draw 1 card and lose 1 point.'
  },
  {
    id: 'sp4a',
    category: 'Special',
    name: 'Mouna (Skip)',
    points: 0,
    ruler: null,
    symbol: '🤫',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next',
    detail: 'Mouna means silence. The next player loses their entire turn and must immediately draw 1 card (-1 point penalty).'
  },
  {
    id: 'sp4b',
    category: 'Special',
    name: 'Mouna (Skip)',
    points: 0,
    ruler: null,
    symbol: '🤫',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next',
    detail: 'Mouna means silence. The next player loses their entire turn and must immediately draw 1 card (-1 point penalty).'
  },
  {
    id: 'sp4c',
    category: 'Special',
    name: 'Mouna (Skip)',
    points: 0,
    ruler: null,
    symbol: '🤫',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next',
    detail: 'Mouna means silence. The next player loses their entire turn and must immediately draw 1 card (-1 point penalty).'
  },
  {
    id: 'sp4d',
    category: 'Special',
    name: 'Mouna (Skip)',
    points: 0,
    ruler: null,
    symbol: '🤫',
    variant: 'mouna',
    type: 'mouna',
    effect: 'skip_next',
    detail: 'Mouna means silence. The next player loses their entire turn and must immediately draw 1 card (-1 point penalty).'
  },
  {
    id: 'sp5a',
    category: 'Special',
    name: 'Chakravyuha (Reverse)',
    points: 0,
    ruler: null,
    symbol: '🌀',
    variant: 'chakra',
    type: 'chakravyuha',
    effect: 'reverse_order',
    detail: 'The legendary spiral military formation. Reverses the turn order immediately (clockwise becomes anticlockwise). Has no effect in 2-player matches.'
  },
  {
    id: 'sp5b',
    category: 'Special',
    name: 'Chakravyuha (Reverse)',
    points: 0,
    ruler: null,
    symbol: '🌀',
    variant: 'chakra',
    type: 'chakravyuha',
    effect: 'reverse_order',
    detail: 'The legendary spiral military formation. Reverses the turn order immediately (clockwise becomes anticlockwise). Has no effect in 2-player matches.'
  },
  {
    id: 'sp6a',
    category: 'Special',
    name: 'Crisis: Famine',
    points: 0,
    ruler: null,
    symbol: '☠️',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_region',
    detail: 'Forces the next player either to play a Region (R) card or Wild, or draw a card and lose 1 point.'
  },
  {
    id: 'sp6b',
    category: 'Special',
    name: 'Crisis: Famine',
    points: 0,
    ruler: null,
    symbol: '☠️',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_region',
    detail: 'Forces the next player either to play a Region (R) card or Wild, or draw a card and lose 1 point.'
  },
  {
    id: 'sp7a',
    category: 'Special',
    name: 'Crisis: Nadir Shah',
    points: 0,
    ruler: null,
    symbol: '🗡️',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_marvel',
    detail: 'Forces the next player either to play a Marvel (M) card or Wild, or draw a card and lose 1 point.'
  },
  {
    id: 'sp7b',
    category: 'Special',
    name: 'Crisis: Nadir Shah',
    points: 0,
    ruler: null,
    symbol: '🗡️',
    variant: 'crisis',
    type: 'crisis',
    effect: 'force_marvel',
    detail: 'Forces the next player either to play a Marvel (M) card or Wild, or draw a card and lose 1 point.'
  }
];
